"""version 0.1.4"""

CSV_SEPERATOR = " "
DATAFRAME_EXPECTED_COLUMNS = 5
DEVICE_INDEX = 0
CHANNEL_WIDTH_INDEX = 1
GATE_SOURCE_VOLAGE_INDEX = 2
DRAIN_SOURCE_VOLTAGE_INDEX = 3
DEVICE_DTYPE = "int64"
CHANNEL_WIDTH_DTYPE = "int64"
VOLTAGE_CURRENT_D_TYPE = "float64"
DEVICE_MINIMUM_VALUE = 1
