"""version 0.1.1"""

CSV_SEPERATOR = " "
DATAFRAME_EXPECTED_COLUMNS = 5
DEVICE_INDEX = 0
CHANNEL_WIDTH_INDEX = 1
DEVICE_DTYPE = "int64"
CHANNEL_WIDTH_DTYPE = "int64"
VOLTAGE_CURRENT_D_TYPE = "float64"
